# config/packages/vich.yaml
vich_uploader:
    db_driver: orm # or mongodb or phpcr

    metadata:
      type: attribute

    mappings:
      articlesImage:
        uri_prefix: /image/article
        upload_destination: "%kernel.project_dir%/public/image/article"
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer



