controllers:
    resource: ../src/Controller/
    type: attribute

main:
    path: /
    controller: App\Controller\MainController::index

# app_createCategorie:
#     path: /categorie/createCategorie
#     controller: App\Controller\CategorieController::createCategorie

app_createCategorie:
    path: '/categorie/createCategorie'
    controller: 'App\Controller\CategorieController::createCategorie'

app_createType:
    path: /type
    controller: App\Controller\TypeController::createType
    # methods: GET

app_createMarque:
    path: '/marque/createMarque'
    controller: 'App\Controller\MarqueController::createMarque'


# app_createType:
#     path: '/type/createType'
#     controller: 'App\Controller\TypeController::createType'

app_article_create:
    path: /Article/create
    controller: App\Controller\ArticleController::create
    methods: [GET, POST]


app_read:
    path: /Article/lire
    controller: App\Controller\ArticleController::lire


app_delete:
    path: /delete/{id}
    controller: App\Controller\ArticleController::delete
    methods: [GET]


app_view:
    path: /voir/{id}
    controller: App\Controller\ArticleController::voir
    methods: [GET]